server:
  port: ${SERVER_PORT:8123}
spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILE:dev}
  cloud:
    config:
      allow-override: true
      override-none: true
      override-system-properties: false
      server:
        git:
          clone-on-start: true
          basedir: ${user.home}/git
          username: config-server
          password: glpat-XZDuCDGk9rzyqPNs4zWk
          uri: https://gitlab.com/startup_team1/configuration.git
          skip-ssl-validation: true

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"